DROP TABLE IF EXISTS needles;

CREATE TABLE needles (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    due_date DEFAULT NULL
);